# Generated by Django 2.2.10 on 2022-05-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_remove_resume_jobid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobexp',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='exp',
        ),
    ]
